import ReceiptStatusBadge from './ReceiptStatusBadge';

const formatActionTime = (value, fallback = 'Not yet') => {
  if (!value) return fallback;
  return new Date(value).toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });
};

const ActionButton = ({ children, onClick, variant = 'ghost', disabled = false }) => (
  <button
    type="button"
    className={`crm-payments-${variant}-btn`}
    onClick={onClick}
    disabled={disabled}
  >
    {children}
  </button>
);

const ReceiptDeliveryPanel = ({
  receipt,
  recipientEmail,
  onRecipientEmailChange,
  onGenerateReceipt,
  onRegenerateReceipt,
  onPrintReceipt,
  onDownloadReceipt,
  onEmailReceipt,
  onOpenPayment,
  onOpenCheckout,
  onOpenCustomer,
  isBusy,
  formatDateTime,
}) => {
  if (!receipt) return null;

  const canEmail = Boolean(recipientEmail);
  const needsReceipt = receipt.receiptStatus === 'Pending';

  return (
    <section className="crm-receipts-panel crm-receipts-delivery-panel">
      <header className="crm-receipts-panel-head">
        <div>
          <p className="crm-receipts-kicker">Delivery & Actions</p>
          <h3>{needsReceipt ? 'Prepare and send the first receipt' : 'Receipt delivery control'}</h3>
        </div>
        <ReceiptStatusBadge status={receipt.receiptStatus || 'Pending'} />
      </header>

      <div className="crm-receipts-delivery-summary">
        <article>
          <p>Selected Receipt</p>
          <strong>{receipt.receiptNumber || 'Pending'}</strong>
        </article>
        <article>
          <p>Receipt Status</p>
          <strong>{receipt.receiptStatus || 'Pending'}</strong>
        </article>
        <article>
          <p>Payment Status</p>
          <strong>{receipt.paymentStatus || 'Pending'}</strong>
        </article>
      </div>

      <label className="crm-receipts-field">
        <span>Recipient Email</span>
        <input
          type="email"
          value={recipientEmail}
          onChange={(event) => onRecipientEmailChange(event.target.value)}
          placeholder="customer@email.com"
        />
      </label>

      {!canEmail ? (
        <p className="crm-receipts-inline-note">
          No customer email is available yet. Open the customer profile to add one before emailing the receipt.
        </p>
      ) : null}

      <div className="crm-receipts-delivery-log">
        <article>
          <p>Printed</p>
          <strong>{formatActionTime(receipt.printedAt, 'Not printed')}</strong>
        </article>
        <article>
          <p>Downloaded</p>
          <strong>{formatActionTime(receipt.downloadedAt, 'Not downloaded')}</strong>
        </article>
        <article>
          <p>Emailed</p>
          <strong>{formatActionTime(receipt.emailedAt, 'Not emailed')}</strong>
        </article>
      </div>

      <div className="crm-receipts-action-stack">
        {needsReceipt ? (
          <ActionButton variant="primary" onClick={onGenerateReceipt} disabled={isBusy}>
            {isBusy ? 'Generating...' : 'Generate Receipt'}
          </ActionButton>
        ) : (
          <ActionButton variant="primary" onClick={onRegenerateReceipt} disabled={isBusy}>
            {isBusy ? 'Refreshing...' : 'Regenerate Receipt'}
          </ActionButton>
        )}
        <ActionButton variant="secondary" onClick={onPrintReceipt} disabled={isBusy || !receipt.receiptNumber}>
          Print Receipt
        </ActionButton>
        <ActionButton variant="secondary" onClick={onDownloadReceipt} disabled={isBusy || !receipt.receiptNumber}>
          Download PDF
        </ActionButton>
        <ActionButton variant="primary" onClick={onEmailReceipt} disabled={isBusy || !receipt.receiptNumber || !canEmail}>
          Email Receipt
        </ActionButton>
        <ActionButton variant="ghost" onClick={onOpenPayment}>
          Open Linked Payment
        </ActionButton>
        <ActionButton variant="ghost" onClick={onOpenCheckout}>
          Open Linked Checkout
        </ActionButton>
        <ActionButton variant="ghost" onClick={onOpenCustomer}>
          Open Customer Profile
        </ActionButton>
      </div>

      <div className="crm-receipts-delivery-foot">
        <article>
          <p>Generated By</p>
          <strong>{receipt.generatedBy || 'Front Desk'}</strong>
        </article>
        <article>
          <p>Generated At</p>
          <strong>{formatDateTime(receipt.issuedAt || receipt.paymentDate)}</strong>
        </article>
        <article>
          <p>Linked Payment</p>
          <strong>{receipt.paymentId || 'Unlinked'}</strong>
        </article>
      </div>

    </section>
  );
};

export default ReceiptDeliveryPanel;
