import ReceiptStatusBadge from './ReceiptStatusBadge';

const SummaryItem = ({ label, value }) => (
  <article className="crm-receipts-summary-item">
    <p>{label}</p>
    <strong>{value || '-'}</strong>
  </article>
);

const ReceiptTransactionSummary = ({ receipt }) => {
  if (!receipt) return null;

  return (
    <section className="crm-receipts-summary-strip">
      <div className="crm-receipts-summary-strip-head">
        <div>
          <p className="crm-receipts-kicker">Receipt Summary</p>
          <h2>Transaction context at a glance</h2>
        </div>
        <div className="crm-receipts-summary-strip-badges">
          <ReceiptStatusBadge status={receipt.paymentStatus || 'Pending'} />
          <ReceiptStatusBadge status={receipt.receiptStatus || 'Pending'} />
        </div>
      </div>

      <div className="crm-receipts-summary-grid">
        <SummaryItem label="Receipt No." value={receipt.receiptNumber} />
        <SummaryItem label="Payment ID" value={receipt.paymentId} />
        <SummaryItem label="Checkout ID" value={receipt.checkoutId || '-'} />
        <SummaryItem label="Appointment ID" value={receipt.appointmentId || '-'} />
        <SummaryItem label="Customer" value={receipt.customerName} />
        <SummaryItem label="Branch" value={receipt.branchName || 'Main Branch'} />
        <SummaryItem label="Payment Method" value={receipt.method || 'Cash'} />
        <SummaryItem label="Payment Status" value={receipt.paymentStatus || 'Pending'} />
        <SummaryItem label="Generated By" value={receipt.generatedBy || 'Front Desk'} />
        <SummaryItem label="Receipt Status" value={receipt.receiptStatus || 'Pending'} />
      </div>
    </section>
  );
};

export default ReceiptTransactionSummary;

