services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: spa_saloon
      POSTGRES_USER: spa_saloon
      POSTGRES_PASSWORD: spa_saloon
    ports:
      - '5432:5432'
    volumes:
      - spa_saloon_pgdata:/var/lib/postgresql/data

volumes:
  spa_saloon_pgdata:
