export const SALON_NAME = 'Hazel Beauty Saloon';
export const CRM_NAME = `${SALON_NAME} CRM`;
export const BRAND_TAGLINE = 'Where Beauty Meets Perfection';
export const SALON_INITIALS = 'HB';
export const BRAND_DOMAIN = 'hazelbeautysaloon.com';
export const BRAND_CONTACT_EMAIL = `hello@${BRAND_DOMAIN}`;
export const BRAND_BOOKING_EMAIL = `bookings@${BRAND_DOMAIN}`;
export const BRAND_OPERATIONS_EMAIL = `operations@${BRAND_DOMAIN}`;
export const BRAND_FRONTDESK_EMAIL = `frontdesk@${BRAND_DOMAIN}`;
export const BRAND_WEBSITE = `www.${BRAND_DOMAIN}`;
export const BRAND_BOOKING_URL = `${BRAND_WEBSITE}/book`;
export const BRAND_ADDRESS = '8422 Melrose Ave, West Hollywood, CA 90069';
export const BRAND_PHONE = '(323) 555-0188';
export const BRAND_BOOKING_PHONE = '(323) 555-0177';
export const BRAND_MAP_LINK = 'https://maps.google.com/?q=8422+Melrose+Ave+West+Hollywood+CA+90069';
